### ISSUE TITLE
AWS Driver does not return credentials with machine_batch

### ISSUE THREAD

**Issue by bbbco** [chef/chef-provisioning-aws#260]
I am having trouble getting machine_batch to work with chef-provisioning-aws 1.3.0 and chef-provisioning 1.2.1

Here's my output:

````
Converging 1 resources
Recipe: @recipe_files::/home/bbbco/chef/trunk/provisioning/qa-next-aws.rb
  * machine_batch[default] action converge[2015-07-23T18:55:13-04:00] INFO: Processing machine_batch[default] action converge (@recipe_files::/home/bbbco/chef/trunk/provisioning/qa-next-aws.rb line 28)
[2015-07-23T18:55:13-04:00] WARN: Class Chef::Provider::MachineBatch does not declare 'resource_name :machine_batch'.
[2015-07-23T18:55:13-04:00] WARN: This will no longer work in Chef 13: you must use 'resource_name' to provide DSL.
[2015-07-23T18:55:14-04:00] WARN: Resource.dsl_name is deprecated and will be removed in Chef 13.  Use resource_name instead.

    
    ================================================================================
    Error executing action `converge` on resource 'machine_batch[default]'
    ================================================================================
    
    NoMethodError
    -------------
    undefined method `[]' for nil:NilClass
    
    Resource Declaration:
    ---------------------
    # In /home/bbbco/chef/trunk/provisioning/qa-next-aws.rb
    
     28: machine_batch do
     29:   0.upto(2) do |i|
     30:     machine "#{deployment}-backend-#{i}" do
     31:       add_machine_options bootstrap_options: {
     32:         instance_type: 'm3.large'
     33:       }
     34:       #binding.pry
     35:       file '/etc/chef/attributes.json', { :content => "{\n  \"deployment\": \"#{deployment}\"\n }" }
     36:       # blah blah
     37:       file '/mnt/blah/blah', { :content => '' }
     38:       recipe 'blah'
     39:     end
     40:   end
     41: end
    
    Compiled Resource:
    ------------------
    # Declared in /home/bbbco/chef/trunk/provisioning/qa-next-aws.rb:28:in `from_file'
    
    machine_batch("default") do
      action [:converge]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      driver "aws"
      chef_server {:chef_server_url=>"https://chef-qa", :options=>{:client_name=>"bbbco", :signing_key_filename=>"/home/bbbco/.chef/bbbco.pem"}}
      machine_options {:bootstrap_options=>{:key_name=>"bbbco-aws", :image_id=>"ami-a661e1ce", :instance_type=>"m3.xlarge", :security_group_ids=>["QA", "sg-b4682add"], :availability_zone=>"us-east-1b"}, :convergence_options=>{:ssl_verify_mode=>:verify_none, :chef_config=>"json_attribs '/etc/chef/attributes.json'\nenvironment 'qa-bleeding-edge'\nOhai::Config[:plugin_path] << '/etc/chef/ohai_plugins'\nChef::Config[:yum_timeout] = 900\n"}, :ssh_username=>"root"}
      declared_type :machine_batch
      cookbook_name "@recipe_files"
      recipe_name "/home/bbbco/chef/trunk/provisioning/qa-next-aws.rb"
      machines ["qa-next-aws-backend-0", "qa-next-aws-backend-1", "qa-next-aws-backend-2"]
    end
    
[2015-07-23T18:55:14-04:00] WARN: Resource.dsl_name is deprecated and will be removed in Chef 13.  Use resource_name instead.
[2015-07-23T18:55:14-04:00] INFO: Running queued delayed notifications before re-raising exception

Running handlers:
[2015-07-23T18:55:14-04:00] ERROR: Running exception handlers
Running handlers complete
[2015-07-23T18:55:14-04:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 7.332850888 seconds
[2015-07-23T18:55:14-04:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2015-07-23T18:55:14-04:00] ERROR: machine_batch[default] (@recipe_files::/home/bbbco/chef/trunk/provisioning/qa-next-aws.rb line 28) had an error: NoMethodError: undefined method `[]' for nil:NilClass
[2015-07-23T18:55:14-04:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
````

and here is the chef stack trace:

````
 $ cat /var/chef/cache/chef-stacktrace.out
Generated at 2015-07-23 18:55:14 -0400
NoMethodError: machine_batch[default] (@recipe_files::/home/bbbco/chef/trunk/provisioning/qa-next-aws.rb line 28) had an error: NoMethodError: undefined method `[]' for nil:NilClass
/home/bbbco/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/chef-provisioning-aws-1.3.0/lib/chef/provisioning/aws_driver/driver.rb:57:in `initialize'
/home/bbbco/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/chef-provisioning-aws-1.3.0/lib/chef/provisioning/aws_driver/driver.rb:45:in `new'
/home/bbbco/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/chef-provisioning-aws-1.3.0/lib/chef/provisioning/aws_driver/driver.rb:45:in `from_url'
/home/bbbco/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/chef-provisioning-1.2.1/lib/chef/provisioning.rb:83:in `driver_for_url'
/home/bbbco/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/chef-provisioning-1.2.1/lib/chef/provisioning/chef_run_data.rb:105:in `driver_for_url'
/home/bbbco/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/chef-provisioning-1.2.1/lib/chef/provisioning/chef_run_data.rb:84:in `driver_for'
/home/bbbco/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/chef-provisioning-1.2.1/lib/chef/provider/machine_batch.rb:131:in `block in by_new_driver'
/home/bbbco/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/chef-provisioning-1.2.1/lib/chef/provider/machine_batch.rb:124:in `each'
/home/bbbco/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/chef-provisioning-1.2.1/lib/chef/provider/machine_batch.rb:124:in `by_new_driver'
/home/bbbco/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/chef-provisioning-1.2.1/lib/chef/provider/machine_batch.rb:27:in `block in <class:MachineBatch>'
/home/bbbco/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/chef-12.4.1/lib/chef/provider/lwrp_base.rb:61:in `instance_eval'
/home/bbbco/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/chef-12.4.1/lib/chef/provider/lwrp_base.rb:61:in `recipe_eval_with_update_check'
/home/bbbco/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/chef-12.4.1/lib/chef/provider/lwrp_base.rb:46:in `block in action'
/home/bbbco/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/chef-provisioning-1.2.1/lib/chef/provider/machine_batch.rb:93:in `with_ready_machines'
/home/bbbco/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/chef-provisioning-1.2.1/lib/chef/provider/machine_batch.rb:50:in `block in <class:MachineBatch>'
/home/bbbco/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/chef-12.4.1/lib/chef/provider/lwrp_base.rb:61:in `instance_eval'
/home/bbbco/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/chef-12.4.1/lib/chef/provider/lwrp_base.rb:61:in `recipe_eval_with_update_check'
/home/bbbco/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/chef-12.4.1/lib/chef/provider/lwrp_base.rb:46:in `block in action'
/home/bbbco/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/chef-12.4.1/lib/chef/provider.rb:140:in `run_action'
/home/bbbco/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/chef-12.4.1/lib/chef/resource.rb:584:in `run_action'
/home/bbbco/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/chef-12.4.1/lib/chef/runner.rb:49:in `run_action'
/home/bbbco/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/chef-12.4.1/lib/chef/runner.rb:81:in `block (2 levels) in converge'
/home/bbbco/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/chef-12.4.1/lib/chef/runner.rb:81:in `each'
/home/bbbco/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/chef-12.4.1/lib/chef/runner.rb:81:in `block in converge'
/home/bbbco/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/chef-12.4.1/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
/home/bbbco/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/chef-12.4.1/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/home/bbbco/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/chef-12.4.1/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/home/bbbco/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/chef-12.4.1/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/home/bbbco/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/chef-12.4.1/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/home/bbbco/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/chef-12.4.1/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/home/bbbco/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/chef-12.4.1/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
/home/bbbco/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/chef-12.4.1/lib/chef/runner.rb:80:in `converge'
/home/bbbco/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/chef-12.4.1/lib/chef/client.rb:654:in `block in converge'
/home/bbbco/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/chef-12.4.1/lib/chef/client.rb:649:in `catch'
/home/bbbco/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/chef-12.4.1/lib/chef/client.rb:649:in `converge'
/home/bbbco/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/chef-12.4.1/lib/chef/client.rb:688:in `converge_and_save'
/home/bbbco/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/chef-12.4.1/lib/chef/client.rb:269:in `run'
/home/bbbco/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/chef-12.4.1/lib/chef/application.rb:270:in `block in fork_chef_client'
/home/bbbco/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/chef-12.4.1/lib/chef/application.rb:258:in `fork'
/home/bbbco/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/chef-12.4.1/lib/chef/application.rb:258:in `fork_chef_client'
/home/bbbco/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/chef-12.4.1/lib/chef/application.rb:224:in `block in run_chef_client'
/home/bbbco/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/chef-12.4.1/lib/chef/local_mode.rb:39:in `with_server_connectivity'
/home/bbbco/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/chef-12.4.1/lib/chef/application.rb:212:in `run_chef_client'
/home/bbbco/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/chef-12.4.1/lib/chef/application/client.rb:402:in `block in interval_run_chef_client'
/home/bbbco/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/chef-12.4.1/lib/chef/application/client.rb:392:in `loop'
/home/bbbco/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/chef-12.4.1/lib/chef/application/client.rb:392:in `interval_run_chef_client'
/home/bbbco/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/chef-12.4.1/lib/chef/application/client.rb:382:in `run_application'
/home/bbbco/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/chef-12.4.1/lib/chef/application.rb:60:in `run'
/home/bbbco/.rvm/rubies/ruby-2.1.0/lib/ruby/gems/2.1.0/gems/chef-12.4.1/bin/chef-client:26:in `<top (required)>'
/home/bbbco/.rvm/gems/ruby-2.1.0/bin/chef-client:23:in `load'
/home/bbbco/.rvm/gems/ruby-2.1.0/bin/chef-client:23:in `<main>'
/home/bbbco/.rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:15:in `eval'
/home/bbbco/.rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:15:in `<main>'
````

It seems like the `machine[:spec].driver_url` is getting set to "aws:aws", which the `Chef::Provisioning::AWSDriver::Driver` init doesn't handle well, as I don't have an aws profile called "aws". Here is how I am using the driver:

````
  5 with_driver 'aws'
  6 
  7 # Consistent Deployment name
  8 deployment = "qa-next-aws"
  9 
 10 with_machine_options(
 11   :bootstrap_options=> {
 12     :key_name => 'bbbco-aws',
 13     :image_id => 'ami-a661e1ce',
 14     # non-HVM image
 15     #:image_id => 'ami-16c6bb7e',
 16     :instance_type => 'm3.xlarge',
 17     :security_group_ids => ['QA', 'sg-b4682add'], #QA and default non-VPC group
 18     :availability_zone => 'us-east-1b'
 19   },
 20   :convergence_options => {
 21     :ssl_verify_mode => :verify_none,
 22     :chef_config => "json_attribs \'/etc/chef/attributes.json\'\nenvironment \'qa-bleeding-edge\'\nOhai::Config[:plugin_path] << \'/etc/chef/ohai_plugins\'\nChef::Config[:yum_timeout] = 900\n"
 23   },
 24   :ssh_username => 'root'
 25 )
````

**Comment by gmiranda23** [comment]
I believe the syntax for with_driver has changed to require a region in it.  What happens if you try `with_driver "aws::us-east-1"` ?

**Comment by bbbco** [comment]
Yeah, I tried both `aws::us-east-1` and `aws:default:us-east-1` with the same errors.

**Comment by bbbco** [comment]
@lynchc was able to help point me in the right direction on gitter.im

````
lynchc: I’ve gotten that error before. it was when I was provisioning a system that already existed from a different version
when I did a knife node edit on it, I would see that the driver_url was set to aws:aws
manually set it to just “aws” and the error goes away
if that doesn’t work, paste the full stack trace and we’ll see if we can figure it out

bbbco: @lynchc I did post the full stack trace on chef/chef-provisioning-aws#260

lynchc: @bbbco do a knife node edit for the instance you’re trying to provision. I had that exact same error because it was created with an older version that had set the drvier_url to “aws:aws"
@bbbco any luck?

bbbco: no, I had updated the chef-provisioning and chef-provision-aws to the latest versions before provisioning these nodes
Hmmm ... I looked more into it, and apparently you're right @lynchc ! A few of those nodes were using an outdated version of the gem stuffed away somewhere on my computer.

lynchc: good stuff. I’ve run into that a few times myself. glad it all worked out

bbbco: Thanks so much for your help in pointing me to the right direction!
````
