### ISSUE TITLE
Load Balancer deletion not working in 1.0.0.rc.1

### ISSUE THREAD

**Issue by danieljimenez** [chef/chef-provisioning-aws#171]
```
  * load_balancer[skylab-app] action destroy
    
    ================================================================================
    Error executing action `destroy` on resource 'load_balancer[skylab-app]'
    ================================================================================
    
    NoMethodError
    -------------
    undefined method `destroy_load_balancer' for nil:NilClass
    
    Resource Declaration:
    ---------------------
    # In /Users/djimenez/Development/metal/recipes/destroy_all.rb
    
      6: load_balancer 'skylab-app' do
      7:   action :destroy
      8: end
      9: 
    
    Compiled Resource:
    ------------------
    # Declared in /Users/djimenez/Development/metal/recipes/destroy_all.rb:6:in `from_file'
    
    load_balancer("skylab-app") do
      action [:destroy]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      chef_server {:chef_server_url=>"http://localhost:8889", :options=>{:client_name=>"calculon.center.foreflight.com", :signing_key_filename=>nil}}
      declared_type :load_balancer
      cookbook_name "@recipe_files"
      recipe_name "/Users/djimenez/Development/metal/recipes/destroy_all.rb"
    end
```

**Comment by danieljimenez** [comment]
Seems like deleting the data bag and recreating it fixed the deletion problem.
