### ISSUE TITLE
AWS Security Groups cannot be tagged

### ISSUE THREAD

**Issue by tyler-ball** [chef/chef-provisioning-aws#204]
```
NoMethodError
-------------
undefined method `aws_tags' for Chef::Resource::AwsSecurityGroup
```

We need to do a check in aws_provider.rb to make sure classes respond to `aws_tags` before we try and read it.  This is also broken for anyone who doesn't extend `AWSResourceWithEntry`.

Bug introduced by https://github.com/chef/chef-provisioning-aws/pull/194

\cc @patrick-wright @danieljimenez

**Comment by patrick-wright** [comment]
@tyler-ball are you taking point on this?

**Comment by tyler-ball** [comment]
@patrick-wright yup!  I'll tag you on the review

**Comment by dblessing** [comment]
I pulled your latest changes and still get this error with a standard `AWSResource`.

**Comment by tyler-ball** [comment]
@dblessing we found that the only objects which supported tagging were ones that extended `AWSResourceWithEntry` - which resource are you trying to tag?

**Comment by dblessing** [comment]
@tyler-ball I'm not trying to tag anything. My new resource extends AWSResource and throws an error about `undefined method 'aws_tags'` just like above. See resource and my temporary hack to make things work at https://github.com/chef/chef-provisioning-aws/pull/212/files#diff-3864ee77687d50983e65a71fe73da2f4R13 It's hitting the aws_tags part of `aws_provider.rb`

**Comment by tyler-ball** [comment]
@dblessing you're right - I totally didn't fix this issue.  Re-opened!

**Comment by tyler-ball** [comment]
This should be closed by the 1.2.1 release - re-open if it isn't!
